steps:
- script: echo Release ID: $(Release.ReleaseId)
  displayName: 'Log Release ID'

- task: Docker@2
  displayName: Login to Docker Registry
  inputs:
    command: login
    containerRegistry: $(serviceConnection) # Variable from variable group will not work here

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    Dockerfile: $(dockerFile)
    repository: $(registryService)/$(repoNameAsImageName)
    arguments: --no-cache
    tags: $(tag)

- task: Docker@2
  displayName: Push Docker Image
  inputs:
    command: push
    repository: $(registryService)/$(repoNameAsImageName)
    tags: $(tag)
  condition: and(succeeded(), ne(variables.isPullRequest, true))
