steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(azureSubscription)
    appType: 'webAppContainer'
    WebAppName: $(appServiceName)
    DockerNamespace: $(registryServer)
    DockerRepository: $(registryRepository)
    DockerImageTag: $(tag)
    StartupCommand: 'pnpm start:prod'
