variables:
  - name: nodeVersion
    value: '18.x'
  - name: isDev
    value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['System.PullRequest.TargetBranch'], 'develop'))]
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
  - name: dockerFile
    value: Dockerfile
  - name: tag
    value: dev
  - group: bid-admin-api-demo-dev

jobs:
- job: BuildJob
  displayName: 'Build Job'
  steps:
    # Extract the repo name without the github org or account name
    - script: |
        repo_name=$(echo $(Build.Repository.Name) | rev | cut -d'/' -f 1 | rev)
        echo "##vso[task.setvariable variable=repoNameAsImageName]$repo_name"
      displayName: 'Parse repo name'
    - template: common-build-steps.yml
- job: DeployJob
  dependsOn: BuildJob
  condition: and(succeeded(), ne(variables.isPullRequest, true), eq(variables.isDev, true))
  steps:
  - template: common-deploy-steps.yml
