# Trigger pipeline from branches
trigger:
  branches:
    include:
    - main

# Trigger pipeline from PRs. Currently, has to be configured in Azure DevOps settings for it to fully work
pr:
  autoCancel: true
  branches:
    include:
      - main

# Environment to use
pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: nodeVersion
    value: '18.x'
  - name: isProd
    value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['System.PullRequest.TargetBranch'], 'main'))]
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
  - name: dockerFile
    value: Dockerfile
  - name: tag
    value: prod
  - group: bid-admin-api-demo-prod

stages:
# Build Stage
- stage: BuildStage
  displayName: 'Build Stage for Prod'
  condition: eq(variables.isProd, true)
  jobs:
  - job: BuildJob
    steps:
      # Extract the repo name without the github org or account name
      - script: |
          repo_name=$(echo $(Build.Repository.Name) | rev | cut -d'/' -f 1 | rev)
          echo "##vso[task.setvariable variable=repoNameAsImageName]$repo_name"
        displayName: 'Parse repo name'
      - template: common-build-steps.yml
# Deployment Stage
- stage: DeployStage
  displayName: 'Deploy Stage for Prod'
  condition: and(succeeded(), ne(variables.isPullRequest, true), eq(variables.isProd, true))
  dependsOn: BuildStage
  jobs:
  - job: DeployJob
    steps:
    - template: common-deploy-steps.yml
