steps:
# - task: Docker@2
#   displayName: Build Docker Image
#   inputs:
#     repository: $(Build.Repository.Name) 
#     command: build
#     Dockerfile: Dockerfile
#     tags: $(tagName)

- script: |
    echo $(Build.Repository.Name)
    echo $(Build.SourceBranchName)
  displayName: 'Run a one-line script'
