steps:
- task: Docker@2
  displayName: Login to Docker Registry
  inputs:
    command: login
    containerRegistry: $(serviceConnection) # Variable from variable group will not work here
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(azureSubscription)
    appType: 'webAppContainer'
    WebAppName: $(appServiceName)
    DockerNamespace: $(registryServer)
    DockerRepository: $(registryRepository)
    DockerImageTag: $(tag) # replace with your Docker image tag
    StartupCommand: 'pnpm start:prod'
