steps:
- script: echo $(repoNameAsImageName)
  displayName: 'Print repo name.'

- task: Docker@2
  displayName: Login to Docker Registry
  inputs:
    command: login
    containerRegistry: $(serviceConnection) # Variable from variable group will not work here

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    Dockerfile: $(dockerFile)
    repository: $(CONTAINER_REGISTRY_SERVER)/$(repoNameAsImageName)
    arguments: --no-cache
    tags: $(tag)

- task: Docker@2
  displayName: Push Docker Image
  inputs:
    command: push
    repository: $(CONTAINER_REGISTRY_SERVER)/$(repoNameAsImageName)
    tags: $(tag)
  condition: and(succeeded(), ne(variables.isPullRequest, true), or(eq(variables.isDev, true), eq(variables.isProd, true)))
