steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1'
    appType: 'webAppContainer'
    WebAppName: 'bid-admin-api-demo-dev' # replace with your Azure web app name
    DockerNamespace: 'rmademo.azurecr.io' # replace with your Docker ID
    DockerRepository: 'rmademo.azurecr.io/bid-admin-api' # replace with your Docker repository name
    DockerImageTag: $(tag) # replace with your Docker image tag
