steps:
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    Dockerfile: $(dockerFile)
    repository: $(dockerImage)
    arguments: --no-cache
    tags: $(dockerTag)

# - script: |
#     echo $(Build.Repository.Name)
#     echo $(Build.SourceBranchName)
#   displayName: 'Run a one-line script'

# - task: Docker@2
#   displayName: Push Docker Image
#   inputs:
#     # repository: $(containerRegistry)/$(imageRepository)
#     repository: rmademo/$(Build.Repository.Name)
#     command: push
#     Dockerfile: $(dockerFile)
#     tags: $(dockerTag)

- task: Docker@2
  displayName: Push Docker Image
  inputs:
    command: push
    repository: rmademo.azurecr.io/$(dockerImage)
    tags: $(dockerTag)
