steps:
- task: Docker@2
  displayName: Login to Docker Registry
  inputs:
    command: login
    containerRegistry: 'Bid Admin API Demo Docker DevOps Service Connection'

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    Dockerfile: $(dockerFile)
    repository: $(dockerImage)
    container: rmademo
    arguments: --no-cache
    tags: $(dockerTag)

- task: Docker@2
  displayName: Push Docker Image
  inputs:
    command: push
    repository: rmademo.azurecr.io/$(dockerImage)
    tags: $(dockerTag)
