steps:
- task: Docker@2
  displayName: Login to Docker Registry
  inputs:
    command: login
    containerRegistry: $(serviceConnection) # Variable from variable group will not work here
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (a9b787cf-7a6e-4c05-a790-adc3bf941755)'
    appType: 'webAppContainer'
    WebAppName: 'bid-admin-api-demo-dev' # replace with your Azure web app name
    DockerNamespace: 'rmademo.azurecr.io' # replace with your Docker ID
    DockerRepository: 'rmademo.azurecr.io/bid-admin-api' # replace with your Docker repository name
    DockerImageTag: $(tag) # replace with your Docker image tag
    StartupCommand: 'pnpm start:prod'
