steps:
- task: Docker@2
  displayName: Login to Docker Registry
  inputs:
    command: login
    containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION)

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    Dockerfile: $(dockerFile)
    repository: $(CONTAINER_REGISTRY_SERVER)/$(repoNameAsImageName)
    arguments: --no-cache
    tags: $(tag)

- task: Docker@2
  displayName: Push Docker Image
  inputs:
    command: push
    repository: $(CONTAINER_REGISTRY_SERVER)/$(repoNameAsImageName)
    tags: $(tag)
