# Trigger pipeline from branches
trigger:
  branches:
    include:
    - develop

# Trigger pipeline from PRs. Currently, has to be configured in Azure DevOps settings for it to fully work
pr:
  autoCancel: true
  branches:
    include:
      - develop

# Environment to use
pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: nodeVersion
    value: '18.x'
  - name: isDev
    value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['System.PullRequest.TargetBranch'], 'develop'))]
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
  - name: dockerFile
    value: Dockerfile
  - name: serviceConnection
    value: 'Bid Admin API Demo Docker DevOps Service Connection'
  - name: tag
    value: dev
  - group: bid-admin-api-demo-dev

stages:
- stage: BuildStage
  displayName: 'Build Stage for Dev'
  condition: eq(variables.isDev, true)
  jobs:
  - job: BuildJob
    steps:
      # Extract the repo name without the github org or account name
      - script: |
          repo_name=$(echo $(Build.Repository.Name) | rev | cut -d'/' -f 1 | rev)
          echo "##vso[task.setvariable variable=repoNameAsImageName]$repo_name"
      - template: common-steps-azure-pipelines.yml

- stage: DeployStage
  displayName: 'Deploy Stage for Dev'
  condition: and(succeeded(), ne(variables.isPullRequest, true), eq(variables.isDev, true))
  dependsOn: BuildStage
  jobs:
  - job: DeployJob
    steps:
    - template: common-deploy-steps-azure-pipelines.yml
