# Trigger pipeline from branches
trigger:
  branches:
    include:
    - develop

# Trigger pipeline from PRs. Currently, has to be configured in Azure DevOps settings for it to fully work
pr:
  autoCancel: true
  branches:
    include:
      - develop

# Environment to use
pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'
  isDev: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['System.PullRequest.TargetBranch'], 'develop'))]
  isPullRequest: $[ eq(variables['Build.Reason'], 'PullRequest') ]
  dockerFile: Dockerfile
  serviceConnection: 'Bid Admin API Demo Docker DevOps Service Connection'
  tag: dev
  - group: bid-admin-api-demo-dev

stages:
- stage: BuildStage
  displayName: 'Build Stage for Dev'
  condition: eq(variables.isDev, true)
  jobs:
  - job: BuildJob
    steps:
      # Extract the repo name without the github org or account name
      - script: |
          repo_name=$(echo $(Build.Repository.Name) | rev | cut -d'/' -f 1 | rev)
          echo "##vso[task.setvariable variable=repoNameAsImageName]$repo_name"
      - template: common-steps-azure-pipelines.yml

# - job: BuildStepsForProd
#   displayName: 'Build Steps for Prod'
#   condition: eq(variables.isProd, true)
#   variables:
#     # App variables stored in Azure DevOps. Will be automatically injected during build
#     - group: bid-portal-demo-prod
#     - name: artifactName
#       value: artifact-prod
#   steps:
#     - template: common-steps-azure-pipelines.yml
